[font]
normal = { family = "CaskaydiaCove Nerd Font", style = "Regular" }
size = 13.0

[colors.primary]
background = "#1a1b26"
foreground = "#c0caf5"

[window]
decorations = "None"
padding = { x = 20, y = 20 }  # Optional: Innenabstand f√ºr bessere Optik
dynamic_padding = true
opacity = 0.95                # Optional: Transparenz
